<a href="https://colab.research.google.com/github/Sophiajackrich/Hamoye_Repo/blob/main/Hamoye_Stage_B's_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
# READ IN DATA
en_data = pd.read_csv("/content/energydata_complete.csv")
en_data.head(3)

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  

[3 rows x 29 columns]

#### Data Exploration

In [4]:
en_data.shape

(19735, 29)

In [5]:
en_data.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [6]:
en_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [7]:
en_col = en_data.columns

In [8]:
en_col.unique()

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [9]:
en_col.nunique()

29

In [10]:
en_data.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [11]:
en_data.duplicated().sum()

0

In [12]:
en_data.describe()

Appliances        lights            T1          RH_1            T2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958      3.801875     21.686571     40.259739     20.341219   
std      102.524891      7.935988      1.606066      3.979299      2.192974   
min       10.000000      0.000000     16.790000     27.023333     16.100000   
25%       50.000000      0.000000     20.760000     37.333333     18.790000   
50%       60.000000      0.000000     21.600000     39.656667     20.000000   
75%      100.000000      0.000000     22.600000     43.066667     21.500000   
max     1080.000000     70.000000     26.260000     63.360000     29.856667   

               RH_2            T3          RH_3            T4          RH_4  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      40.420420     22.267611     39.242500     20.855335     39.026904   
std        4.069813      2.006111      3.254576      2.042884      4.341321   
min       20.463333     17.200000     28.766667     15.100000     27.660000   
25%       37.900000     20.790000     36.900000     19.530000     35.530000   
50%       40.500000     22.100000     38.530000     20.666667     38.400000   
75%       43.260000     23.290000     41.760000     22.100000     42.156667   
max       56.026667     29.236000     50.163333     26.200000     51.090000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 28 columns]

In [13]:
en_data.describe().T.head(3)

count       mean         std    min    25%   50%    75%      max
Appliances  19735.0  97.694958  102.524891  10.00  50.00  60.0  100.0  1080.00
lights      19735.0   3.801875    7.935988   0.00   0.00   0.0    0.0    70.00
T1          19735.0  21.686571    1.606066  16.79  20.76  21.6   22.6    26.26

#### QUIZ ASSESSMENT

In [26]:
# en_data_1 = en_data.drop(['date', 'lights'], axis = 1)


#####Dropped date and lights because it wont fit in my application of normalization and other regression models isnt presently important in my model

In [27]:
# # Applying normalization to the data
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()

# en_norm = pd.DataFrame(scaler.fit_transform(en_data_1), columns = en_data_1.columns)
# en_norm.head(2)

Appliances       T1      RH_1        T2      RH_2        T3      RH_3  \
0    0.046729  0.32735  0.566187  0.225345  0.684038  0.215188  0.746066   
1    0.046729  0.32735  0.541326  0.225345  0.682140  0.215188  0.748871   

         T4      RH_4        T5  ...        T9      RH_9     T_out  \
0  0.351351  0.764262  0.175506  ...  0.223032  0.677290  0.372990   
1  0.351351  0.782437  0.175506  ...  0.226500  0.678532  0.369239   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.097674  0.894737    0.50000    0.953846   0.538462  0.265449  0.265449  
1     0.100000  0.894737    0.47619    0.894872   0.533937  0.372083  0.372083  

[2 rows x 27 columns]

In [29]:
# # Seperating the traing and testing data
# X = en_norm.drop('Appliances', axis = 1)
# y = en_norm['Appliances']

In [30]:
# # Importing traintestsplit
# from sklearn.model_selection import train_test_split

# # Seperat data into train-test-split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =2)

In [31]:
# Question 17
temp_in_rm = np.array(en_norm['T2'])
temp_out_rm = np.array(en_norm['T6'])


In [32]:
temp_out_rm

array([0.3810702 , 0.37544268, 0.36748654, ..., 0.86426042, 0.82952506,
       0.78858002])

In [33]:
temp_in = temp_in_rm.reshape(-1, 1)
temp_in_train, temp_in_test, temp_out_train, temp_out_test = train_test_split(temp_in, temp_out_rm, test_size = 0.3, random_state =42)

In [35]:
# Instantiate model
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
#fit the model to the training dataset
linear_model.fit(temp_in_train, temp_out_train)
#obtain predictions
predicted_values = linear_model.predict(temp_in_test)

In [36]:
predicted_values

array([0.23928945, 0.46794238, 0.23108472, ..., 0.3001772 , 0.4297256 ,
       0.3217686 ])

In [37]:
from sklearn.metrics import r2_score
r2 = r2_score(temp_out_test, predicted_values)
print(f"Root Mean Sq is:", round(r2, 3))

Root Mean Sq is: 0.643


In [38]:
# Question 18
en_data_1 = en_data.drop(['date', 'lights'], axis = 1)
# Seperating the traing and testing data
X = en_norm.drop('Appliances', axis = 1)
y = en_norm['Appliances']
# Importing traintestsplit
from sklearn.model_selection import train_test_split

# Seperat data into train-test-split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =42)
# Applying normalization to the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

en_train_norm = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)
en_train_norm.head(2)

en_test_norm = pd.DataFrame(scaler.fit_transform(X_test), columns = X_test.columns)
en_test_norm.head(2)

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0  0.432946  0.226056  0.121256  0.525822  0.257531  0.344068  0.421992   
1  0.538543  0.715999  0.379109  0.700066  0.369488  0.970847  0.492022   

       RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0  0.279447  0.312320  0.329517  ...  0.451579  0.413025  0.217204   
1  0.568580  0.223559  0.435614  ...  0.135789  0.630252  0.247312   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.920869  0.844444   0.179487    0.953846   0.295988  0.512678  0.512678  
1     0.588053  0.866667   0.230769    0.400000   0.350492  0.469695  0.469695  

[2 rows x 26 columns]

In [39]:
en_train_norm.head(2)

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0  0.497360  0.283004  0.122850  0.585114  0.373878  0.303474  0.476577   
1  0.286167  0.576864  0.188999  0.693396  0.217957  0.735317  0.270270   

       RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0  0.239968  0.408027  0.155065  ...  0.475893  0.376380  0.168810   
1  0.681016  0.178691  0.330033  ...  0.240375  0.703504  0.262594   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.863125  0.776316   0.142857    0.984615   0.193182  0.724509  0.724509  
1     0.836758  0.807018   0.142857    0.600000   0.343939  0.864018  0.864018  

[2 rows x 26 columns]

In [40]:
# Question 18
# Instantiate model
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
#fit the model to the training dataset
linear_model.fit(X_train, y_train)
#obtain predictions
pred_test_val= linear_model.predict(X_test)
pred_train_val= linear_model.predict(X_train)


In [41]:
print(pred_test_val)
print(pred_train_val)

[0.03322207 0.24411599 0.03400024 ... 0.06844707 0.10032325 0.05722198]
[0.03736239 0.08440778 0.02815806 ... 0.04623579 0.08713294 0.07302946]


In [47]:
# Question 18 solu
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, pred_train_val)
print(f'The mean absolute error is', (round(mae, 3)))

The mean absolute error is 0.05


In [48]:
# Question 19
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_train, pred_train_val)
rmse = np.sqrt(rmse)
print(f'The mean absolute error is', (round(rmse, 3)))

The mean absolute error is 0.089


In [49]:
# Question 20(Test set using MAE)
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, pred_test_val)
print(f'The mean absolute error is', (round(mae, 3)))

The mean absolute error is 0.05


In [50]:
# Question 21(Test set using RMSE)
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_test, pred_test_val)
rmse = np.sqrt(rmse)
print(f'The mean absolute error is', (round(rmse, 3)))

The mean absolute error is 0.088


In [ ]:
# Yes the test model overfits to the training set

##### Ridge regression question

In [53]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(X_train, y_train)
pred_test= ridge_reg.predict(X_test)
pred_train= ridge_reg.predict(X_train)

# Question 23(Test set using RMSE)
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_test, pred_test)
rmse = np.sqrt(rmse)
print(f'The mean absolute error is', (round(rmse, 3)))

# No difference with ridge regression model from linear model

The mean absolute error is 0.088


In [58]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
#comparing the effects of regularisation
def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

# Question 24(Test set using RMSE)
linear_model_weights = get_weights_df(linear_model, X_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, X_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, X_train, 'Lasso_weight')
final_weight = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

# 25 FEATURES HAVE NON-ZERO FEAUITURE WEIGHTS

In [59]:
final_weight

Features  Linear_Model_Weight  Ridge_Weight
0          RH_2            -0.456698     -0.401134
1         T_out            -0.321860     -0.250765
2            T2            -0.236178     -0.193880
3            T9            -0.189941     -0.188584
4          RH_8            -0.157595     -0.156596
5        RH_out            -0.077671     -0.050541
6          RH_7            -0.044614     -0.046291
7          RH_9            -0.039800     -0.041701
8            T5            -0.015657     -0.020727
9            T1            -0.003281     -0.021549
10          rv1             0.000770      0.000743
11          rv2             0.000770      0.000743
12  Press_mm_hg             0.006839      0.006516
13           T7             0.010319      0.010021
14   Visibility             0.012307      0.012032
15         RH_5             0.016006      0.016176
16         RH_4             0.026386      0.024168
17           T4             0.028981      0.027006
18    Windspeed             0.029183      0.030463
19         RH_6             0.038049      0.035023
20         RH_3             0.096048      0.094976
21           T8             0.101995      0.100754
22    Tdewpoint             0.117758      0.076668
23           T6             0.236425      0.213316
24           T3             0.290627      0.287408
25         RH_1             0.553547      0.511932

In [57]:
final_weights

Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.401134     -0.000000
1         T_out            -0.321860     -0.250765      0.000000
2            T2            -0.236178     -0.193880      0.000000
3            T9            -0.189941     -0.188584     -0.000000
4          RH_8            -0.157595     -0.156596     -0.000110
5        RH_out            -0.077671     -0.050541     -0.049557
6          RH_7            -0.044614     -0.046291     -0.000000
7          RH_9            -0.039800     -0.041701     -0.000000
8            T5            -0.015657     -0.020727     -0.000000
9            T1            -0.003281     -0.021549      0.000000
10          rv1             0.000770      0.000743     -0.000000
11          rv2             0.000770      0.000743     -0.000000
12  Press_mm_hg             0.006839      0.006516     -0.000000
13           T7             0.010319      0.010021     -0.000000
14   Visibility             0.012307      0.012032      0.000000
15         RH_5             0.016006      0.016176      0.000000
16         RH_4             0.026386      0.024168      0.000000
17           T4             0.028981      0.027006     -0.000000
18    Windspeed             0.029183      0.030463      0.002912
19         RH_6             0.038049      0.035023     -0.000000
20         RH_3             0.096048      0.094976      0.000000
21           T8             0.101995      0.100754      0.000000
22    Tdewpoint             0.117758      0.076668      0.000000
23           T6             0.236425      0.213316      0.000000
24           T3             0.290627      0.287408      0.000000
25         RH_1             0.553547      0.511932      0.017880

In [60]:
# Question 25(lasso reg)
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
test_pred= lasso_reg.predict(X_test)
train_pred= lasso_reg.predict(X_train)

# Test set using RMSE
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_test, test_pred)
rmse = np.sqrt(rmse)
print(f'The mean absolute error is', (round(rmse, 3)))

The mean absolute error is 0.094
